server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/hui?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat;日志用的filter:log4j;防御sql注入的filter:wall
      filters: stat
      #初始化时建立物理连接的个数
      initial-size: 1
      #最小连接池数量
      min-idle: 1
      #最大连接池数量
      max-active: 20
      #获取连接时最大等待时间
      max-wait: 60000
      #是否缓存preparedStatement
      pool-prepared-statements: false
      #用来检测连接是否有效的sql
      validation-query: select 'x'
      #申请连接时执行validationQuery检测连接是否有效
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效
      test-on-return: false
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      time-between-eviction-runs-millis: 6000
      min-evictable-idle-time-millis: 30000
      max-open-prepared-statements: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.hui.*: debug
    org.springfromework.web: debug
    org.mybatis: debug
  file: D:\test\szcst_logs


